[package]
name = "graphics"
version = "0.1.0"
authors = ["willdejs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit_input_helper = "*"
inflate = "0.4.5"
glium = "0.30.1"
